name: Validate documentation

on:
  pull_request:
    paths:
      - 'docs/**'
    branches:
      - master
  workflow_dispatch:

env:
  # Stop wasting time caching packages
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  # Disable sending usage data to Microsoft
  DOTNET_CLI_TELEMETRY_OPTOUT: true

jobs:
  test:
    runs-on: windows-latest

    name: Building documentation
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup .NET Core @ Latest
        uses: actions/setup-dotnet@v1.7.2
        with:
          dotnet-version: '5.0.x'

      - name: Build code samples for documentation
        run: dotnet test "samples/Samples" -c Release

      - name: Download docfx
        run: |
          $docfx_url=(Invoke-WebRequest -URI 'https://api.github.com/repos/dotnet/docfx/releases/latest' | ConvertFrom-Json).assets.browser_download_url
          Invoke-WebRequest -Uri $docfx_url -OutFile "./docfx.zip"
          Expand-Archive -LiteralPath "./docfx.zip" -DestinationPath "./docfx-bin/"
        shell: powershell

      - name: Build documentation
        run: docfx-bin/docfx.exe docs/docfx.json --warningAsErrors true
